# Generated by Django 4.1.7 on 2023-03-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='blog')),
                ('author', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
