# Generated by Django 4.1.7 on 2023-03-25 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='is_published',
            new_name='is_solved',
        ),
    ]
